// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuYSnovHJM7SL3f4rVDvyT5xbDUVAM6IE',
    appId: '1:773802057726:web:78f3e9f5aca7f97bda2aaf',
    messagingSenderId: '773802057726',
    projectId: 'easy-flutterfir',
    authDomain: 'easy-flutterfir.firebaseapp.com',
    storageBucket: 'easy-flutterfir.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDctFmkXzRxIal2Y6PDSdAHXSS3Xl3OXfc',
    appId: '1:773802057726:android:b3cf8e14a8f135edda2aaf',
    messagingSenderId: '773802057726',
    projectId: 'easy-flutterfir',
    storageBucket: 'easy-flutterfir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXkkwphXTlWO4ZFCQYMrWQNFEWLYluLcI',
    appId: '1:773802057726:ios:780b550cb4403c91da2aaf',
    messagingSenderId: '773802057726',
    projectId: 'easy-flutterfir',
    storageBucket: 'easy-flutterfir.appspot.com',
    iosClientId: '773802057726-f2tkpk6lercehreiu1b02acu8gm7qp5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.eas',
  );
}
